apiVersion: apps/v1
kind: statefulset
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-database
  template:
    metadata:
      labels:
        app: app-database
    spec:
      containers:
      - name: dbcont
        image: sujeethvaddi/phpapp:dbimage
        ports:
        - containerPort: 3306

        #configmap integration
        envFrom:
        - secretRef:
            name: bankapp-db-secret
        
        #Resource quota integration
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        #Liveness probe integration
        livenessProbe:
          httpGet: 
             path: /
             port: 80
          initialDelaySeconds: 30
          PeriodSeconds: 5  
        
        #VolumesMount
        volumeMounts:
        - name: pvc-1
          mountPath: /var/lib/mysql

      volumeClaimTemplates:
      - metadata:
          name: pvc-1
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 2Gi